import { Mailing } from '@/types/mailings';

export const mockMailings: Mailing[] = [
  {
    id: 'mail-1',
    name: 'Weihnachts-Newsletter 2024',
    subject: 'Frohe Weihnachten - Exklusive Filmhighlights für Sie',
    content: '<p>Frohe Weihnachten!</p>',
    customer_filter: 'all',
    status: 'sent',
    campaign: 'Weihnachts-Special 2024',
    date: '2024-12-10',
    sendTime: '09:00',
    recipients: 15420,
    opens: 8945,
    clicks: 3421,
    bounces: 127,
    unsubscribes: 23,
    is_archived: false,
    isArchived: false,
  },
  {
    id: 'mail-2',
    name: 'Oscar-Nominierte Filme',
    subject: 'Die heißesten Oscar-Anwärter jetzt im Kino',
    content: '<p>Oscar-Anwärter</p>',
    customer_filter: 'regular',
    status: 'sent',
    campaign: 'Oscar-Nominierte',
    date: '2024-12-08',
    sendTime: '14:30',
    recipients: 12890,
    opens: 7234,
    clicks: 2876,
    bounces: 89,
    unsubscribes: 15,
    is_archived: false,
    isArchived: false,
  },
  {
    id: 'mail-3',
    name: 'Neujahrs-Vorschau 2025',
    subject: 'Ihre Filmhighlights im neuen Jahr',
    content: '<p>Neues Jahr</p>',
    customer_filter: 'all',
    status: 'scheduled',
    campaign: 'Neujahrsaktion',
    date: '2024-12-28',
    sendTime: '10:00',
    recipients: 16200,
    opens: 0,
    clicks: 0,
    bounces: 0,
    unsubscribes: 0,
    is_archived: false,
    isArchived: false,
  },
  {
    id: 'mail-4',
    name: 'Black Friday Sale',
    subject: 'Black Friday: 30% auf alle Tickets!',
    content: '<p>Black Friday</p>',
    customer_filter: 'all',
    status: 'sent',
    campaign: 'Black Friday 2024',
    date: '2024-11-29',
    sendTime: '08:00',
    recipients: 18450,
    opens: 12340,
    clicks: 5670,
    bounces: 156,
    unsubscribes: 45,
    is_archived: false,
    isArchived: false,
  },
  {
    id: 'mail-5',
    name: 'Familien-Sonntag Aktion',
    subject: 'Jeden Sonntag: Familienrabatt im Kino',
    content: '<p>Familienrabatt</p>',
    customer_filter: 'all',
    status: 'sent',
    date: '2024-12-05',
    sendTime: '11:00',
    recipients: 9870,
    opens: 5234,
    clicks: 1890,
    bounces: 67,
    unsubscribes: 12,
    is_archived: false,
    isArchived: false,
  },
  {
    id: 'mail-6',
    name: 'Wochenprogramm KW 50',
    subject: 'Ihr Kinoprogramm für die Woche',
    content: '<p>Wochenprogramm</p>',
    customer_filter: 'all',
    status: 'sent',
    date: '2024-12-09',
    sendTime: '16:00',
    recipients: 14230,
    opens: 6789,
    clicks: 2345,
    bounces: 98,
    unsubscribes: 18,
    is_archived: false,
    isArchived: false,
  },
  {
    id: 'mail-7',
    name: 'Valentinstag Spezial',
    subject: 'Romantische Filme zum Valentinstag',
    content: '<p>Valentinstag</p>',
    customer_filter: 'all',
    status: 'draft',
    date: '2025-02-10',
    sendTime: '09:00',
    recipients: 15000,
    opens: 0,
    clicks: 0,
    bounces: 0,
    unsubscribes: 0,
    is_archived: false,
    isArchived: false,
  },
  {
    id: 'mail-8',
    name: 'Halloween Special 2024',
    subject: 'Gruselige Filme zur Halloween-Nacht',
    content: '<p>Halloween</p>',
    customer_filter: 'all',
    status: 'sent',
    date: '2024-10-25',
    sendTime: '18:00',
    recipients: 13560,
    opens: 8234,
    clicks: 3456,
    bounces: 112,
    unsubscribes: 28,
    is_archived: true,
    isArchived: true,
  },
  {
    id: 'mail-9',
    name: 'Sommerkino-Auftakt',
    subject: 'Open-Air Kino startet diese Woche',
    content: '<p>Sommerkino</p>',
    customer_filter: 'all',
    status: 'sent',
    date: '2024-06-15',
    sendTime: '10:00',
    recipients: 11890,
    opens: 6234,
    clicks: 2123,
    bounces: 89,
    unsubscribes: 22,
    is_archived: true,
    isArchived: true,
  },
];

export function calculateMailingStats(mailing: Mailing) {
  if (mailing.recipients === 0) {
    return {
      openRate: 0,
      clickRate: 0,
      bounceRate: 0,
      unsubscribeRate: 0,
    };
  }

  return {
    openRate: (mailing.opens / mailing.recipients) * 100,
    clickRate: (mailing.clicks / mailing.recipients) * 100,
    bounceRate: (mailing.bounces / mailing.recipients) * 100,
    unsubscribeRate: (mailing.unsubscribes / mailing.recipients) * 100,
  };
}
