import { Rectangle, RectangleCampaign } from '@/types/rectangles';

export const mockCampaigns: RectangleCampaign[] = [
  {
    id: 'camp-1',
    name: 'Weihnachts-Special 2024',
    startDate: '2024-12-01',
    endDate: '2024-12-31',
    status: 'active',
  },
  {
    id: 'camp-2',
    name: 'Neujahrsaktion',
    startDate: '2025-01-01',
    endDate: '2025-01-31',
    status: 'scheduled',
  },
  {
    id: 'camp-3',
    name: 'Oscar-Nominierte',
    startDate: '2024-11-01',
    endDate: '2024-12-15',
    status: 'active',
  },
];

export const mockRectangles: Rectangle[] = [
  {
    id: 1,
    position: 1,
    isActive: true,
    isCentrallyManaged: true,
    campaignName: 'Weihnachts-Special 2024',
    imageUrl: 'https://images.pexels.com/photos/3030268/pexels-photo-3030268.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/filme/weihnachten',
    linkType: 'attribute',
    linkedAttributeType: 'genre',
  },
  {
    id: 2,
    position: 2,
    isActive: true,
    isCentrallyManaged: false,
    imageUrl: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/filme/action',
    linkType: 'attribute',
    linkedAttributeType: 'genre',
  },
  {
    id: 3,
    position: 3,
    isActive: true,
    isCentrallyManaged: true,
    campaignName: 'Oscar-Nominierte',
    imageUrl: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/filme/oscar-2024',
    linkType: 'film',
  },
  {
    id: 4,
    position: 4,
    isActive: true,
    isCentrallyManaged: false,
    imageUrl: 'https://images.pexels.com/photos/1157557/pexels-photo-1157557.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/angebote/popcorn',
    linkType: 'none',
  },
  {
    id: 5,
    position: 5,
    isActive: true,
    isCentrallyManaged: false,
    imageUrl: 'https://images.pexels.com/photos/2507007/pexels-photo-2507007.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/filme/drama',
    linkType: 'attribute',
    linkedAttributeType: 'genre',
  },
  {
    id: 6,
    position: 6,
    isActive: true,
    isCentrallyManaged: true,
    campaignName: 'Weihnachts-Special 2024',
    imageUrl: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/geschenkgutscheine',
    linkType: 'none',
  },
  {
    id: 7,
    position: 7,
    isActive: false,
    isCentrallyManaged: false,
  },
  {
    id: 8,
    position: 8,
    isActive: true,
    isCentrallyManaged: false,
    imageUrl: 'https://images.pexels.com/photos/1236701/pexels-photo-1236701.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/filme/horror',
    linkType: 'attribute',
    linkedAttributeType: 'genre',
  },
  {
    id: 9,
    position: 9,
    isActive: true,
    isCentrallyManaged: false,
    imageUrl: 'https://images.pexels.com/photos/1200450/pexels-photo-1200450.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/filme/scifi',
    linkType: 'showing',
  },
  {
    id: 10,
    position: 10,
    isActive: false,
    isCentrallyManaged: false,
  },
  {
    id: 11,
    position: 11,
    isActive: true,
    isCentrallyManaged: true,
    campaignName: 'Oscar-Nominierte',
    imageUrl: 'https://images.pexels.com/photos/2726370/pexels-photo-2726370.jpeg?auto=compress&cs=tinysrgb&w=300&h=200',
    targetUrl: '/filme/oscar',
    linkType: 'film',
  },
  {
    id: 12,
    position: 12,
    isActive: false,
    isCentrallyManaged: false,
  },
];
